public enum RoadType {
    CEMENT_NEW,
    CEMENT_TRAVELLED,
    CEMENT_POLISHED,
    ASPHALT_NEW,
    ASPHALT_TRAVELLED,
    ASPHALT_POLISHED,
    ASPHALT_EXCESS,
    GRAVEL_PACKED,
    GRAVEL_LOOSE,
    CINDERS_PACKED,
    ROCK_CRUSHED,
    ICE_SMOOTH,
    SNOW_PACKED,
    SNOW_LOOSE
}
